<a href="https://colab.research.google.com/github/nachopodesta/numpy-library-for-data-science/blob/main/Numpy_Library_for_Data_Science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Library for data science (All in one)

### https://github.com/nachopodesta/


In [1]:
import numpy as np

## Functions

In [10]:
a = np.array([1,2,3,4,5])
b = np.array([[1,2],[3,4]])
c = np.array([7,8,9,6], "complex")

In [3]:
a

array([1, 2, 3, 4, 5])

In [7]:
b

array([[1, 2],
       [3, 4]])

In [11]:
c

array([7.+0.j, 8.+0.j, 9.+0.j, 6.+0.j])

## Arange()

In [17]:
#np.arange?
#arange(star,stop,skip,dtype)

a = np.arange(1,7,2)

In [18]:
a

array([1, 3, 5])

In [20]:
b = np.arange(5.0)

In [21]:
b

array([0., 1., 2., 3., 4.])

In [22]:
c = np.arange(2,20,2)

In [23]:
c

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])