<a href="https://colab.research.google.com/github/nachopodesta/numpy-library-for-data-science/blob/main/Numpy_Library_for_Data_Science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Library for data science (All in one)

### https://github.com/nachopodesta/


In [1]:
import numpy as np

## Functions

In [77]:
a = np.array([1,2,3,4,5])
b = np.array([[1,2],[3,4]])
c = np.array([7,8,9,6], "complex")

In [78]:
a

array([1, 2, 3, 4, 5])

In [79]:
b

array([[1, 2],
       [3, 4]])

In [80]:
c

array([7.+0.j, 8.+0.j, 9.+0.j, 6.+0.j])

## Arange()

In [81]:
#np.arange?
#arange(star,stop,skip,dtype)

a = np.arange(1,7,2)
a

array([1, 3, 5])

In [82]:
b = np.arange(5.0)
b

array([0., 1., 2., 3., 4.])

In [83]:
c = np.arange(2,20,2)
c

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [84]:
d = np.arange(10, dtype="complex")
d

array([0.+0.j, 1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j, 7.+0.j,
       8.+0.j, 9.+0.j])

## Ones, zeros and empty function


In [85]:
a = np.zeros(6)
a

array([0., 0., 0., 0., 0., 0.])

In [86]:
b = np.zeros(4,dtype="int")
b

array([0, 0, 0, 0])

In [87]:
c = np.zeros((2,3))
c

array([[0., 0., 0.],
       [0., 0., 0.]])

In [88]:
d = np.zeros([2,3])
d

array([[0., 0., 0.],
       [0., 0., 0.]])

In [89]:
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [90]:
b = np.ones([3,3])
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [91]:
a = np.empty(6, dtype="float")
a

array([0., 0., 0., 0., 0., 0.])

In [92]:
b = np.empty([2,2], dtype="int")
b

array([[4607182418800017408, 4611686018427387904],
       [4613937818241073152, 4616189618054758400]])

## Lindspace function

In [93]:
a = np.linspace(1,40,num=5)
a

array([ 1.  , 10.75, 20.5 , 30.25, 40.  ])

In [94]:
b = np.linspace(1,50,num=5,endpoint=False)
b

array([ 1. , 10.8, 20.6, 30.4, 40.2])

In [95]:
c = np.linspace(1,10,num=2,dtype="int")
c

array([ 1, 10])

In [96]:
d = np.linspace(1,50,num=5,retstep=True)
d

(array([ 1.  , 13.25, 25.5 , 37.75, 50.  ]), 12.25)

## Identity and eye function

In [97]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [98]:
b = np.eye(4,5)
b

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [99]:
c = np.eye(3,k=-1)
c

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [100]:
d = np.eye(3,k=1)
d

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [101]:
e = np.eye(4,k=2,dtype="int")
e

array([[0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [102]:
#identity

f = np.identity(3,dtype="int")
f

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

## Atributes of array