<a href="https://colab.research.google.com/github/nachopodesta/numpy-library-for-data-science/blob/main/Numpy_Library_for_Data_Science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Library for data science (All in one)

### https://github.com/nachopodesta/


In [1]:
import numpy as np

## Functions

In [10]:
a = np.array([1,2,3,4,5])
b = np.array([[1,2],[3,4]])
c = np.array([7,8,9,6], "complex")

In [3]:
a

array([1, 2, 3, 4, 5])

In [7]:
b

array([[1, 2],
       [3, 4]])

In [11]:
c

array([7.+0.j, 8.+0.j, 9.+0.j, 6.+0.j])

## Arange()

In [17]:
#np.arange?
#arange(star,stop,skip,dtype)

a = np.arange(1,7,2)

In [18]:
a

array([1, 3, 5])

In [20]:
b = np.arange(5.0)

In [21]:
b

array([0., 1., 2., 3., 4.])

In [22]:
c = np.arange(2,20,2)

In [23]:
c

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [25]:
d = np.arange(10, dtype="complex")

In [26]:
d

array([0.+0.j, 1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j, 7.+0.j,
       8.+0.j, 9.+0.j])

## Ones, zeros and empty function


In [27]:
a = np.zeros(6)

In [28]:
a

array([0., 0., 0., 0., 0., 0.])

In [29]:
b = np.zeros(4,dtype="int")

In [30]:
b

array([0, 0, 0, 0])

In [31]:
c = np.zeros((2,3))

In [32]:
c

array([[0., 0., 0.],
       [0., 0., 0.]])

In [33]:
d = np.zeros([2,3])

In [34]:
d

array([[0., 0., 0.],
       [0., 0., 0.]])

In [35]:
a = np.ones(5)

In [36]:
a

array([1., 1., 1., 1., 1.])

In [37]:
b = np.ones([3,3])

In [38]:
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [46]:
a = np.empty(6, dtype="float")

In [47]:
a

array([0., 0., 0., 0., 0., 0.])

In [44]:
b = np.empty([2,2], dtype="int")

In [45]:
b

array([[4607182418800017408, 4611686018427387904],
       [4613937818241073152, 4616189618054758400]])

## Lindspace function

In [52]:
a = np.linspace(1,40,num=5)

In [53]:
a

array([ 1.  , 10.75, 20.5 , 30.25, 40.  ])