<a href="https://colab.research.google.com/github/nachopodesta/numpy-library-for-data-science/blob/main/Numpy_Library_for_Data_Science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Library for data science (All in one)

### https://github.com/nachopodesta/

#### https://www.udemy.com/course/numpy-library-for-data-science-all-in-one/


In [1]:
import numpy as np

## Functions

In [77]:
a = np.array([1,2,3,4,5])
b = np.array([[1,2],[3,4]])
c = np.array([7,8,9,6], "complex")

In [78]:
a

array([1, 2, 3, 4, 5])

In [79]:
b

array([[1, 2],
       [3, 4]])

In [80]:
c

array([7.+0.j, 8.+0.j, 9.+0.j, 6.+0.j])

## Arange()

In [81]:
#np.arange?
#arange(star,stop,skip,dtype)

a = np.arange(1,7,2)
a

array([1, 3, 5])

In [82]:
b = np.arange(5.0)
b

array([0., 1., 2., 3., 4.])

In [83]:
c = np.arange(2,20,2)
c

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [84]:
d = np.arange(10, dtype="complex")
d

array([0.+0.j, 1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j, 7.+0.j,
       8.+0.j, 9.+0.j])

## Ones, zeros and empty function


In [85]:
a = np.zeros(6)
a

array([0., 0., 0., 0., 0., 0.])

In [86]:
b = np.zeros(4,dtype="int")
b

array([0, 0, 0, 0])

In [87]:
c = np.zeros((2,3))
c

array([[0., 0., 0.],
       [0., 0., 0.]])

In [88]:
d = np.zeros([2,3])
d

array([[0., 0., 0.],
       [0., 0., 0.]])

In [89]:
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [90]:
b = np.ones([3,3])
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [91]:
a = np.empty(6, dtype="float")
a

array([0., 0., 0., 0., 0., 0.])

In [92]:
b = np.empty([2,2], dtype="int")
b

array([[4607182418800017408, 4611686018427387904],
       [4613937818241073152, 4616189618054758400]])

## Lindspace function

In [93]:
a = np.linspace(1,40,num=5)
a

array([ 1.  , 10.75, 20.5 , 30.25, 40.  ])

In [94]:
b = np.linspace(1,50,num=5,endpoint=False)
b

array([ 1. , 10.8, 20.6, 30.4, 40.2])

In [95]:
c = np.linspace(1,10,num=2,dtype="int")
c

array([ 1, 10])

In [96]:
d = np.linspace(1,50,num=5,retstep=True)
d

(array([ 1.  , 13.25, 25.5 , 37.75, 50.  ]), 12.25)

## Identity and eye function

In [97]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [98]:
b = np.eye(4,5)
b

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [99]:
c = np.eye(3,k=-1)
c

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [100]:
d = np.eye(3,k=1)
d

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [101]:
e = np.eye(4,k=2,dtype="int")
e

array([[0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [102]:
#identity

f = np.identity(3,dtype="int")
f

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

## Atributes of array

In [104]:
a = np.array([1,2,3,4,5])
a.ndim

1

In [106]:
b = np.array([[1,2],[3,4]])
print(b.ndim)
print(b)

2
[[1 2]
 [3 4]]


In [107]:
#shape
a = np.array([[1,2],[3,4]])
print(a.shape)

(2, 2)


In [108]:
#datatype
print(a.dtype)

int64


In [109]:
#item size
print(a.itemsize)

8


## Indexing in array

In [110]:
a = np.array([9,8,7,6,5])
a

array([9, 8, 7, 6, 5])

In [118]:
print(a[0])
print(a[1])
print(a[2])
print(a[-1])
print(a[-2])

9
8
7
5
6


In [122]:
b = np.array([[1,2],[3,4]])
b

array([[1, 2],
       [3, 4]])

In [124]:
print(b[0][0])
print(b[0][1])
print(b[1][0])
print(b[1][1])

1
2
3
4


## Slicing in array

In [125]:
a = np.array([9,8,7,6,5])
a

array([9, 8, 7, 6, 5])

In [132]:
print(a[0:2])
print(a[1:3])
print(a[1:5])
print(a[::2]) 

[9 8]
[8 7]
[8 7 6 5]
[9 7 5]


In [135]:
a[0:5:2]

array([9, 7, 5])

In [134]:
a[:]

array([9, 8, 7, 6, 5])

##Arithmetic Operations

In [140]:
a = np.arange(1,5)
print(a+2)

[3 4 5 6]


In [141]:
print(a*6)

[ 6 12 18 24]


In [142]:
b = np.array([[5,6],[7,8]])

In [143]:
print(b*2)

[[10 12]
 [14 16]]


In [146]:
a = np.arange(1,5)
b = np.array([5,6,7,8])

a+b

array([ 6,  8, 10, 12])

In [147]:
a*b

array([ 5, 12, 21, 32])

## Reshape and resize function

In [148]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [150]:
b = np.reshape(a,(5,2))
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [152]:
c = np.reshape(a,(5,2),order="F")
c

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [154]:
#resize

a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [163]:
print(np.resize(a,(2,3)))

[[0 1 2]
 [3 4 0]]


## Flatten function

In [164]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [168]:
a.flatten()

array([1, 2, 3, 4])

In [170]:
b = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
b

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [171]:
b.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [172]:
b.flatten(order="F")

array([1, 4, 7, 2, 5, 8, 3, 6, 9])

## Ravel function

In [174]:
a = np.array([[2,3],[4,5]])
a

array([[2, 3],
       [4, 5]])

In [175]:
np.ravel(a)

array([2, 3, 4, 5])

In [176]:
np.ravel(a,order="F")

array([2, 4, 3, 5])

In [177]:
b = np.array([[[9,8,7],[6,5,4],[3,2,1]]])
b

array([[[9, 8, 7],
        [6, 5, 4],
        [3, 2, 1]]])

In [180]:
print(np.ravel(b))
print(np.ravel(b,order="F"))

[9 8 7 6 5 4 3 2 1]
[9 6 3 8 5 2 7 4 1]


## Transpose function

In [185]:
a = np.arange(1,11).reshape(5,2)
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [186]:
a.transpose()

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [187]:
print(np.transpose(a).shape)

(2, 5)


In [188]:
b = np.arange(1,25).reshape(2,3,4) #2 array, 3 rows, 4 columns
b

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [190]:
b.shape

(2, 3, 4)

In [191]:
np.transpose(b) #4 array, 3 rows, 2 columns

array([[[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]],

       [[ 4, 16],
        [ 8, 20],
        [12, 24]]])

In [192]:
a = np.arange(1,10)
print(a)
print(np.transpose(a))

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


## Swapaxes function

In [194]:
a = np.array([[11,12],[13,14]])

np.swapaxes(a,0,1)

array([[11, 13],
       [12, 14]])

In [195]:
np.swapaxes(a,1,0)

array([[11, 13],
       [12, 14]])

In [198]:
b = np.array([[1,2,3]])
b.shape

(1, 3)

In [199]:
print(np.swapaxes(b,1,0))

[[1]
 [2]
 [3]]


In [200]:
print(np.swapaxes(b,0,1))

[[1]
 [2]
 [3]]


## Concatenate function

In [201]:
a = np.arange(1,6)
b = np.arange(6)

In [204]:
print(a)
print(b)

[1 2 3 4 5]
[0 1 2 3 4 5]


In [210]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5])

In [213]:
a = np.arange(6)
b = np.arange(7)
c = np.arange(5)

np.concatenate((a,b,c))

array([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4])

In [214]:
a = np.array([1,2])
b = np.array([9,8])

np.concatenate((a,b))

array([1, 2, 9, 8])

In [215]:
a = np.array([4,5,6])
b = np.array([14,15,16])
c = np.array([24,25,26])

np.concatenate((a,b,c))

array([ 4,  5,  6, 14, 15, 16, 24, 25, 26])

## Matrix addition

In [216]:
a = np.array([[1,2],[3,4]])
b = np.array([[21,22],[23,24]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[21 22]
 [23 24]]


In [218]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

print(a+b)

[ 6  8 10 12]


## Matrix multiplication

In [222]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [223]:
print(a*b) #not matrix multiplication

[[ 5 12]
 [21 32]]


In [226]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [227]:
c = np.array([[9,8],[7,6]])
d = np.array([[5,4],[3,2]])

c.dot(d)

array([[69, 52],
       [53, 40]])

## Linear Algebra

In [228]:
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [230]:
b = np.linalg.inv(a)
print(b)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [231]:
c = np.array([5,6,7,8])
print(c)

[5 6 7 8]


In [234]:
#d = np.linalg.inv(c)
#d

## Power of a matrix

In [235]:
a = np.array([[3,4],[5,6]])
b = np.linalg.matrix_power(a,-2)
b

array([[ 14.  ,  -9.  ],
       [-11.25,   7.25]])